# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ScU602xZicJVKDMQc1ftxrqF9MW7TsXI
"""

def calculate_grade(marks):
    if marks >= 90:
        return "A", "Excellent work! 🌟"
    elif marks >= 80:
        return "B", "Very Good! 👍"
    elif marks >= 70:
        return "C", "Good job 🙂"
    elif marks >= 60:
        return "D", "You can do better 💪"
    else:
        return "F", "Keep trying 💡"


name = input("Enter student name: ")

while True:
    marks = int(input("Enter marks (0-100): "))
    if 0 <= marks <= 100:
        break
    else:
        print("Invalid marks! Please enter between 0 and 100")

grade, message = calculate_grade(marks)

print("\n📊 RESULT FOR", name.upper())
print("Marks:", marks, "/100")
print("Grade:", grade)
print("Message:", message)